// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAHZLjZUUU0K-plKZzp8dCQWAhxhLjVFo',
    appId: '1:361115497987:web:9e980b1e2cc5f70b4c0036',
    messagingSenderId: '361115497987',
    projectId: 'crime-reporting-system-cc4b6',
    authDomain: 'crime-reporting-system-cc4b6.firebaseapp.com',
    storageBucket: 'crime-reporting-system-cc4b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR6WynRSBm44KE4Pb3vSu7P97rdpRMbyQ',
    appId: '1:361115497987:android:ee2e0ecafcaed2e04c0036',
    messagingSenderId: '361115497987',
    projectId: 'crime-reporting-system-cc4b6',
    storageBucket: 'crime-reporting-system-cc4b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwYtloGnFob8FME9ZoGaXtv1ePwESYVE',
    appId: '1:361115497987:ios:c30787ebd54b3b5f4c0036',
    messagingSenderId: '361115497987',
    projectId: 'crime-reporting-system-cc4b6',
    storageBucket: 'crime-reporting-system-cc4b6.appspot.com',
    iosClientId: '361115497987-jdlr822o9948jes8u75t3dj226u7tfur.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp',
  );
}
